name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      name: 1. Pass A_FOO in environment to printenv
      env:
        A_FOO: true
      with:
        arguments: printenv --daemon
    - uses: gradle/gradle-build-action@v2
      name: 2. Pass B_FOO in environment to printenv
      env:
        B_FOO: true
      with:
        arguments: printenv --daemon
    - uses: gradle/gradle-build-action@v2
      name: 3. Pass A_FOO in environment to printenv2
      env:
        A_FOO: true
      with:
        arguments: printenv2 --daemon
